### PR TITLE
[feat] added Arch commands

### PR DESCRIPTION
**Pull request by LucasSnatiago**
* Arch systems dependencies added

### CODE REVIEW

**Comment by dlbeer** [comment]
Thanks -- would you be able to wrap the paragraph at 72 characters and then squash into a single commit? Happy for you to force-push again to this same PR.

**Comment by LucasSnatiago** [comment]
Okay!!!
Now it's ready to merge :)

**Comment by dlbeer** [comment]
Looks like the commit is squashed, but there's still the unwrapped line and what looks like a typo on the line starting with "On".

**Comment by LucasSnatiago** [comment]
Sorry, but where is the unwrapped line?
My text editor is showing everything right, I think :P

Gedit:
image

**Comment by dlbeer** [comment]
Looks good now -- thanks.

**Comment by LucasSnatiago** [comment]
Thank you man, for accepting my PR. :)

**Pull request merged**
