### PR TITLE
simio: console can print to file

### PR DESCRIPTION
**Pull request by hosewiejacke**
This is usefull for `tail -f`.

### CODE REVIEW

**Comment by dlbeer** [comment]
This looks like a good idea. However, the implementation you've suggested would leak a file handle if configuration is done more than once. If you can fix this up and check it over carefully, I'd be happy to merge it.

**Comment by hosewiejacke** [comment]
I just added a [check](https://github.com/dlbeer/mspdebug/pull/60/commits/8ce536556aefdc34750c8f464e6de5165fca6cbb#diff-cba03543ec1839e26802adf0ba3bfa4aR107).

**Comment by dlbeer** [comment]
Ok, looks good -- thanks.

**Comment by hosewiejacke** [comment]
Thanks for merging my first PR :relieved:

**Pull request merged**
