### PR TITLE
Add docker images thorugh github action

### PR DESCRIPTION
**Pull request by xoac**
This PR adds CI to build docker images with mspdebug for multiplatform. I have tested it on arm and it worked. I think it could be an easy way to test mspdebug for people. 

You can test it under name `sylwekrapala/mspdebug:docer-image`
If you are interested in this there are some changes we need to do:
- [ ] create scerests `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`
- [ ] rename images

### CODE REVIEW

**Comment by xoac** [comment]
You can check how this action works in this PR source on my fork: https://github.com/xoac/mspdebug/actions

**Comment by dlbeer** [comment]
Thank you for sending this, but as far as I know mspdebug is already packaged on most Linux distributions. I'm not sure I see what this adds, if the purpose is to avoid having to compile?

**Comment by xoac** [comment]
Docker images are used popularly in CI system, especially if tested against hardware. I didn't know mspdebug is packed on most Linux distributions. This makes this PR pointless. 

mspdebug is also in the testing repository on Alpine Linux edge image.
```
apk add mspdebug --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
```

**Comment by xoac** [comment]
Just if sb will be looking for images: https://github.com/xoac/mspdebug-docker

**Pull request closed without merging**
